language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  matrix:
    - DJANGO=Django==1.4.13
    - DJANGO=Django==1.5.8
    - DJANGO=Django==1.6.5
    - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"
    - 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'

install:
  - pip install raven "$DJANGO"

script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven_django --cov-report term-missing

notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
matrix:
  allow_failures:
    - env: 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.4.13
    - python: "3.3"
      env: DJANGO=Django==1.4.13
    - python: "3.4"
      env: DJANGO=Django==1.4.13
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"

